### PR TITLE
Resolving vulnerabilities

### PR DESCRIPTION
**Pull request by sidorchukandrew-lifeway**

### CODE REVIEW

**Comment by sidorchukandrew-lifeway** [comment]
This PR is now ready for review

**Review by fdwilliams — APPROVED** [review]
👍

**Comment by fdwilliams** [comment]
Thanks, @sidorchukandrew-lifeway!

**Comment by sidorchukandrew-lifeway** [comment]
I won't be able to merge the pull request because I don't have write access. But I'm glad I could get rid of the vulnerabilities!

**Comment by fdwilliams** [comment]
> I won't be able to merge the pull request because I don't have write access. But I'm glad I could get rid of the vulnerabilities!

Merged!

**Pull request merged**
